spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    show-sql: off
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      #jdbc-url: jdbc:mariadb://localhost:3306/soccer
      #driver-class-name: org.mariadb.jdbc.Driver
      connection-timeout: 5000
    username: root
    password: Jsyun0415!
    url: jdbc:log4jdbc:mariadb://localhost:3306/soccer
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging:
  level:
    org:
      hibernate:
        type: trace
  config: classpath:logback-spring.xml


